version: '3.7'

services:
  server-php:
    container_name: servidor_php_juanmiguel_cortes
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - ../:/www/html
    stdin_open: true
    links:
      - mariadb-server
    ports:
      - "8050:8000"

  mariadb-server:
    container_name: servidor_db_juanmiguel_cortes
    image: mariadb
    ports:
      - "3356:3306"
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_api_bbdd
    volumes:
      - ../.db_mysql/:/var/lib/mysql